# Generated by Django 3.0.6 on 2020-05-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('sites', models.IntegerField()),
                ('genre_1', models.CharField(max_length=100)),
                ('genre_2', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
