# Generated by Django 3.0.8 on 2020-07-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_bookposition_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookposition',
            name='status',
            field=models.CharField(choices=[('To do', 'To do'), ('In Progress', 'In progress'), ('Done', 'Done')], default='To do', max_length=20),
        ),
    ]
