# Generated by Django 3.0.8 on 2020-08-08 14:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPhoto',
            new_name='UserImage',
        ),
    ]
