GENRE_CHOICES = (
	("N/A", "N/A"),
	("Fantasy", "Fantasy"),
	("Adventure", "Adventure"),
	("Romance", "Romance"),
	("Contemporary", "Contemporary"),
	("Dystopian", "Dystopian"),
	("Mystery", "Mystery"),
	("Horror", "Horror"),
	("Thriller", "Thriller"),
	("Paranormal", "Paranormal"),
	("Historical fiction", "Historical fiction"),
	("Science Fiction", "Science Fiction"),
	("Memoir", "Memoir"),
	("Cooking", "Cooking"),
	("Art", "Art"),
	("Personal", "Personal"),
	("Development", "Development"),
	("Motivational", "Motivational"),
	("Health", "Health"),
	("History", "History"),
	("Travel", "Travel"),
	("Guide", "Guide"),
	("Families & Relationships", "Families & Relationships"),
	("Humor", "Humor"),
	("Children's", "Children's"),
	("Programming", "Programming"),
	("Financials", "Financials")
)

MONTH_CHOICES = (
	("1", "January"),
	("2", "February"),
	("3", "March"),
	("4", "April"),
	("5", "May"),
	("6", "June"),
	("7", "July"),
	("8", "August"),
	("9", "September"),
	("10", "October"),
	("11", "November"),
	("12", "December"),
)

STATUS_CHOICES = (
	("To do", "To do"),
	("In progress", "In progress"),
	("Done", "Done"),
)
